### ISSUE TITLE
Edit Markdown file changeLogs.md

### ISSUE THREAD

**Issue by tameeshB** [tameeshB/pyPing#5]
Copy contents of info from this release: `https://github.com/tameeshB/pyPing/releases/tag/v0.01` into `https://github.com/tameeshB/pyPing/blob/master/docs/changeLogs.md` with the following format:
--------------------**changeLogs.md**--------------------
# Change Logs
## v0.01
<https://github.com/tameeshB/pyPing/releases/tag/v0.01 contents here.>

**Comment by DoctaRay** [comment]
got it

**Comment by buckley-w-david** [comment]
Sorry, didn't notice your comment @DoctaRay until I already submitted a PR
